import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import localFont from "next/font/local";
import "./globals.css";

// ฟอนต์ custom
const petitFormal = localFont({
  src: "../fonts/PetitFormalScript-Regular.ttf",
  variable: "--font-petit-formal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TenantLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} ${petitFormal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}